Models/OrderViewModel.cs
using BABC_Logistics_core.GIS.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BABC_Logistics_core.Models
{
    public class OrderViewModel
    {
        public OrderHead Order;
        public List<Product> SelectableProducts;
        //public List<string> additionalOrders;
        //public List<MaterialRow> materials;
    }

    public class PurchaseOrderViewModel
    {
        public PurchaseOrderHead Order;
        public List<Product> SelectableProducts;
        //public List<string> additionalOrders;
        //public List<MaterialRow> materials;
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BABC_Logistics_core.GIS.DTO;
using BABC_Logistics_core.GIS.Model;
using BABC_Logistics_core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NuGet.Frameworks;

namespace BABC_Logistics_core.Controllers
{
    public class OrderController : Controller
    {
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private OrderModel mOM;
        private BaseDataModel mBDM;
        private LogisticModel mLOM;
        private UserModel mUM;
        private CustomerModel mCM;
        private PrintingModel mPM;
        private BABC_Logistics_core.GIS.Model.ProductModel mPRM;

        private string mGeneralIndexSearchCount = "0";

        public OrderController(IConfiguration config)
        {
            mOM = new OrderModel(config);
            mBDM = new BaseDataModel(config);
            mLOM = new LogisticModel(config);
            mUM = new UserModel(config);
            mCM = new CustomerModel(config);
            mPM = new PrintingModel(config);
            mPRM = new BABC_Logistics_core.GIS.Model.ProductModel(config);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string search_value, string search_type)
        {
            List<OrderHead> lst = new List<OrderHead>();

            if (string.IsNullOrEmpty(search_value))
            {
                return View();
            }

            if (search_type.Equals("Datum"))
            {
                lst = mOM.GetOrderByIdxList("1", "*", "LDT>=" + search_value, false, 20, true);
            }
            else if (search_type.Equals("Kund"))
            {
                lst = mOM.GetOrderByIdxList("2", search_value, "LEF<=4", false, 50, false);
            }
            else if (search_type.Equals("Säljarkod"))
            {
                lst = mOM.GetOrderByIdxList("4", search_value, "*", false, 50, false);
            }

            List<OrderHead> sortedList = lst.OrderByDescending(o => o.OrderNo).ToList();

            ViewBag.search_value = search_value;
            ViewBag.search_type = search_type;

            return View(sortedList);
        }

        public IActionResult PickList(string search_value, string search_value2, string search_type)
        {
            List<OrderHead> lst = new List<OrderHead>();
            StringBuilder filter = new StringBuilder();
            List<OrderHead> tempLst = new List<OrderHead>();
            List<string> additionalLst = new List<string>();
            List<string> checkLst = new List<string>();

            PickListParam olp = new PickListParam();

            int maxOrdersInPicklist = int.MaxValue;
            if (!string.IsNullOrEmpty(ConfigurationManager.AppSetting["MaxOrdersInPicklist"]))
            {
                bool parseOK = int.TryParse(ConfigurationManager.AppSetting["MaxOrdersInPicklist"], out maxOrdersInPicklist);
            }

            // When landing on the page the first time
            if (string.IsNullOrEmpty(search_type))
                return View();

            if (search_type.Equals("supplie"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERS");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = "supplie", ReadFrom = true, UpdateTo = false };
                    }

                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }
            else if (search_type.Equals("pre"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERO");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = "pre", ReadFrom = true, UpdateTo = false };
                    }
                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }
            else if (search_type.Equals("other"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERD");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = "other", ReadFrom = true, UpdateTo = false };
                    }
                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }

            olp.Index = 1;
            olp.IndexFilter = "*";
            olp.IndexCount = int.Parse(mGeneralIndexSearchCount);
            olp.OrderSerie = "A";
            olp.IncludeDeliveredRows = false;
            olp.WithRows = true;
            olp.MaxCount = 50;
            olp.ReverseReading = true;

            try
            {
                List<FilterDTO> filterList = getFilterList("FILTERA");
                if (filterList.Count > 0)
                {
                    olp.AdditionalFilter = parseFilterConstants(filterList[0].Filter);
                }
            }
            catch (Exception e)
            {
                logger.Error("Error setting filter", e);
            }


            //// Additionlorders or ordinary search
            //if (search_type.Equals("customer"))
            //{
            //    olp.Index = 2;
            //    olp.IndexFilter = search_value;

            //    lst = mLOM.GetOrderList(olp);
            //}
            //else
            //{
            //    lst = mLOM.GetOrderListWithAdditionalOrder(olp);
            //}
            lst = mLOM.GetOrderListWithAdditionalOrder(olp);


            List<OrderHead> temp = new List<OrderHead>();
            if (lst != null)
            {
                foreach (OrderHead oh in lst)
                {
                    oh.PreferedDeliverDate = BABC_Logistics_core.Helpers.GeneralFunctions.getDateFromStr(oh.PreferedDeliverDate).ToString("yyyy-MM-dd");
                    oh.IsWholeOrderDeliverable = true;
                    oh.NonDeliverableRows = 0;
                    temp.Add(oh);

                    //foreach (OrderRow or in oh.OrderRows)
                    //{
                    //    if (or.Product != null)
                    //    {
                    //        if (or.Amount.Value <= or.Product.Stock)
                    //            oh.IsWholeOrderDeliverable = true;
                    //        else
                    //        {
                    //            oh.IsWholeOrderDeliverable = false;
                    //            oh.NonDeliverableRows++;
                    //        }
                    //    }
                    //}

                    //if (oh.OrderRows.Count > oh.NonDeliverableRows)
                    //{
                    //    temp.Add(oh);
                    //}

                }
                //temp = CheckTodayOrders(lst);
            }

            //ViewBag.additionalOrders = additionalLst;
            ViewBag.search_value = search_value;
            ViewBag.search_type = search_type;

            List<OrderHead> sortedList = temp.OrderBy(o => o.PickListState)
                .ThenBy(o => o.PreferedDeliverDate)
                .ThenBy(o => o.Date)
                .ThenBy(o => o.Order_ttmm)
                .Take(maxOrdersInPicklist)
                .ToList();

            return View(sortedList);
        }

        public IActionResult Details(string id)
        {
            List<OrderHead> lst = mOM.GetOrderPickList("1", id, "0", "*", "A", true, false, 1, false);
            OrderHead oh = null;
            Dictionary<string, List<MaterialRow>> materials = new Dictionary<string, List<MaterialRow>>();

            if (lst.Count > 0)
                oh = lst[0];
            else
                oh = null;

            if (oh != null)
            {
                BaseTable ls = mBDM.GetBaseTable("03", oh.DeliverWay);
                if (ls != null)
                    oh.DeliverWay = ls.Description;

                BaseTable lv = mBDM.GetBaseTable("02", oh.DeliverTerms);
                if (lv != null)
                    oh.DeliverTermsDescription = lv.Description;

                //Customer customer = mCM.GetCustomerById(oh.DeliverCustomerNo);

                //ViewBag.Customer = customer;

            }

            if (oh.OrderRows == null)
                oh.OrderRows = new List<OrderRow>();

            // Remove all rows without product
            oh.OrderRows.RemoveAll(o => string.IsNullOrEmpty(o.ProductNo));

            logger.Debug("Details materials :" + materials.Count);
            ViewBag.Materials = materials;

            var sortedRows = (from OrderRow r in oh.OrderRows
                              orderby r.Product.WarehouseNo ascending
                              select r).ToList();

            oh.OrderRows = sortedRows;
            oh.isPrioOrder = false;

            return View(oh);
        }



Views/Order/Details.cshtml
@model BABC_Logistics_core.GIS.DTO.OrderHead

@{
	ViewBag.Title = "Details";
}

<meta name="viewport" content="width=device-width, initial-scale=-100%" >
<style>
	#Input {
		width: 200px;
	}

	#Btn {
		margin: 10px 0px;
	}

	#Border {
		border-radius: 20px 70px;
		padding: 30px;
		margin: 10px;
		
		}

	

	.table tr:nth-child(Odd) {
		background: #E7E8EC;
	}

	.table th {
		border-top-color:white;
		background-color: white;
		font-size: 1.5rem;
		font-weight: normal;
	}
	
</style>


<div style="background-color:lightgray" id="Border" width="100%">
	<h1>@BABC_Logistics_core.Language.Resources.Details</h1>
	<table style="width:100%">
		<tr>
			<td><b>@BABC_Logistics_core.Language.Resources.OrderNo: </b>@Model.OrderNo</td>
			<td><b>@BABC_Logistics_core.Language.Resources.DeliveryNote: </b>@Model.LastDeliverNote</td>
			<td><b>@BABC_Logistics_core.Language.Resources.DeliveryMethod: </b>@Model.DeliverWay</td>
			<td><b>@BABC_Logistics_core.Language.Resources.DeliveryTerms: </b>@Model.DeliverTermsDescription</td>
			<td><b>@BABC_Logistics_core.Language.Resources.Weight: </b>@Model.TotalWeight</td>
		</tr>
		<tr>
			<td><b>@BABC_Logistics_core.Language.Resources.Customer: </b> @Model.DeliverCustomerName</td>
			<td><b>@BABC_Logistics_core.Language.Resources.Address1: </b> @Model.DeliverAddress1</td>
			<td><b>@BABC_Logistics_core.Language.Resources.Address2: </b> @Model.DeliverAddress2</td>
			<td><b>@BABC_Logistics_core.Language.Resources.ZipAndCity: </b>@Model.DeliverZipCity</td>

		</tr>
		<tr>
			<td><b>@BABC_Logistics_core.Language.Resources.Info: </b>@Model.Text3</td>
			<td><b>@BABC_Logistics_core.Language.Resources.Text1: </b>@Model.Text1</td>
			<td><b>@BABC_Logistics_core.Language.Resources.Text2: </b>@Model.Text2</td>
		</tr>
	</table>
</div>






<table class="table">
	<tr>
		<th>
		<h4>@BABC_Logistics_core.Language.Resources.Row</h4>
		</th>
		<th>
            <h4>@BABC_Logistics_core.Language.Resources.Product</h4>
		</th>
		<th>
            <h4>@BABC_Logistics_core.Language.Resources.Description</h4>
		</th>
        <th style="text-align:right;">
            <h4>	@BABC_Logistics_core.Language.Resources.PickingAmount</h4>
        </th>
		<th>
            <h4>@BABC_Logistics_core.Language.Resources.Info</h4>
		</th>
		<th>
            <h4>	@BABC_Logistics_core.Language.Resources.Orig</h4>
          </th>
		<th>
            <h4>@BABC_Logistics_core.Language.Resources.Del</h4>
</th>
		<th>
            <h4>	@BABC_Logistics_core.Language.Resources.Stock</h4>
</th>
		<th>
            <h4>	@BABC_Logistics_core.Language.Resources.Unit</h4>
</th>
		<th>
            <h4>	@BABC_Logistics_core.Language.Resources.Warehouse</h4>
		</th>
		<th>
			&nbsp;
		</th>
	</tr>


	@foreach (var item in Model.OrderRows)
    {
        //                string rowClass = "", inputStyle = "";
        bool partDeliver = item.DeliverState.CompareTo("4") == 0 ? true : false;
        bool fullDeliver = item.DeliverState.CompareTo("5") == 0 ? true : false;
        bool somekindOfDeliver = item.DeliverState.CompareTo("0") == 0 ? false : true;
        decimal missingAmount = 0;

        string rowStyle = "";

        if (((item.Amount - item.DeliveredAmount) > item.AmountToDeliver) && !(item.MDF.Equals("1") || item.MDF.Equals("2")))
        {
            //                    rowClass = "";
            //inputStyle = "background-color:rgba(243, 125, 125, 1);";
            missingAmount = item.AmountToDeliver.Value - (item.Amount.Value - item.DeliveredAmount.Value);
        }

        if (fullDeliver)
        {
            rowStyle = "background-image: linear-gradient(to top, #0ba360 0%, #3cba92 100%);colorGrayText";
        }
        else if (partDeliver)
        {
            rowStyle = "background-image: linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%);";
        }

		<tr style="@rowStyle" id="row-@item.RowNo">


			<td>
				@Html.DisplayFor(modelItem => item.RowNo)
			</td>


			<td>
				@Html.DisplayFor(modelItem => item.ProductNo)
			</td>


			<td>


				<div>
					@item.ProductDescription
				</div>
				@if (item.Textrows != null)
				{
					foreach (BABC_Logistics_core.GIS.DTO.OrderRowText t in item.Textrows)
					{
						<div style="font-style:italic;color:gray;">
							@t.Text
						</div>
					}
				}
				@if (item.MDF == "1" || item.MDF == "2")
				{
					if ((ViewBag.Materials as Dictionary<string, List<BABC_Logistics_core.GIS.DTO.MaterialRow>>).ContainsKey(item.OrderNo + item.RowNo.ToString()))
					{
						List<BABC_Logistics_core.GIS.DTO.MaterialRow> mr = (ViewBag.Materials as Dictionary<string, List<BABC_Logistics_core.GIS.DTO.MaterialRow>>)[item.OrderNo + item.RowNo.ToString()];
						<div style="font-style:italic;color:gray;margin-top:5px;border-style:solid;border-width:1px;border-color:lightgray;border-radius:5px;">
							<table style="width:100%;">
								<tr>
									<th style="border-top-width:0px;">
										<b> Material </b>
									</th>
									<th style="border-top-width:0px;">
									</th>
									<th style="border-top-width:0px;text-align:right;">
										Antal
									</th>
								</tr>
								@foreach (BABC_Logistics_core.GIS.DTO.MaterialRow m in mr)
								{
									<tr>
										<td> @m.ProductNo </td>
										<td> @m.ProductDescription </td>
										<td style="text-align:right;"> @m.Amount </td>


									</tr>
								}
							</table>
						</div>
					}
				}
			</td>
			<td style="text-align:right;">
				@if (!fullDeliver)
				{
					<span><b>@(item.Amount - item.DeliveredAmount) </b></span>
				}
				else
				{
					<span> Klar </span>
				}

			</td>
			<td>
				@if (missingAmount != 0)
				{
					<span id="missing-amount-row-@item.RowNo" class="label label-danger">@missingAmount</span>
				}
				<br />
				@if (!item.PreferedDeliverDate.Equals("") && (!item.PreferedDeliverDate.Equals(Model.PreferedDeliverDate)))
				{
					<span id="missing-amount-row-@item.RowNo" class="label label-warning">Lev.dat: @item.PreferedDeliverDate</span>
				}
			</td>
			<td style="text-align:right;">
				<span> @item.Amount </span>
			</td>
			<td style="text-align:right;">
				<span>@item.DeliveredAmount</span>
			</td>
			<td style="text-align:right;">
				<span> @item.Product.Stock </span>
			</td>
			<td style="text-align:right;">
				@Html.DisplayFor(modelItem => item.Unit)
			</td>
			<td style="text-align:right;">
				@if (string.IsNullOrEmpty(item.WarehouseNo))
				{
					if (item.Product != null)
					{
						@item.Product.WarehouseNo
					}
				}
				else
				{
					@item.WarehouseNo
				}
			</td>
			@if (item.MDF.Equals("1") || item.MDF.Equals("2"))
			{
				<td>
					<span class="glyphicon glyphicon-cog tip"></span>
				</td>
			}
			else
			{
				<td> </td>
			}

		</tr>

	}
</table>



<div>
	<form id="frmSign" class="navbar-form" style="display:inline-block;" role="form">
		<div class="form-group">
			@*<label for="exampleInputEmail1">Signatur</label>*@
			<input type="hidden" name="id" value="@Model.OrderNo" />
			<input id="sign" class="form-control uppercase" type="text" placeholder="@BABC_Logistics_core.Language.Resources.Signature" />
		</div>
		<a id="btnPick" class="btn btn-primary btn-default start-button disabled" href=""><span class="glyphicon glyphicon-phone">@BABC_Logistics_core.Language.Resources.PickWithPad</span></a>
	</form>
	<form action="/Order/PrintPickListPDF/" style="margin-left:4px; display:inline-block;">
		<div class="form-group">
			<input class="formDeliverNote" type="hidden" name="id" value="@Model.OrderNo" />
			<input class="formDeliverNote" type="hidden" name="sign" value="" />
			<button id="printButton" type="submit" class="btn btn-success @(Model.PickListState  == "5" ? "disabled" : "")"><span class="glyphicon glyphicon-print"></span>@BABC_Logistics_core.Language.Resources.PrintPickList</button>
		</div>
	</form>

</div>
<div>
</div>
<br />
<form method="post" action="/Order/Picklist">
	<button type="submit" class="btn btn-primary">Back</button>
</form>
@section Scripts {
	<script type="text/JavaScript">

		$(document).ready(function () {
			function validateSignature(signature)
			{
				$.ajax({
					url: '@Url.Action("ValidateSignature", "Order")',
					contentType: "application/json; charset=utf-8",
					data: { sign : signature },
					dataType: "",
					success: successFunc,
					error: errorFunc
				});
			}

			$("#sign").keyup(function () {
				validateSignature($('#sign').val());
			});

			function successFunc(data) {
				if (data == "true")
				{
					$(".start-button").removeClass("disabled");
					$(".start-button").attr("href", "/Order/PickOrder/?id=@Model.OrderNo&sign=" + $('#sign').val());
				}
				else
				{
					$(".start-button").addClass("disabled");
				}
			}

			function errorFunc() {
				$(".start-button").addClass("disabled");
			}
		});
        const getCellValue = (tr, idx) => tr.children[idx].innerText || tr.children[idx].textContent;

        const comparer = (idx, asc) => (a, b) => ((v1, v2) =>
            v1 !== '' && v2 !== '' && !isNaN(v1) && !isNaN(v2) ? v1 - v2 : v1.toString().localeCompare(v2)
        )(getCellValue(asc ? a : b, idx), getCellValue(asc ? b : a, idx));

        // do the work...
        document.querySelectorAll('th').forEach(th => th.addEventListener('click', (() => {
            const table = th.closest('table');
            Array.from(table.querySelectorAll('tr:nth-child(n+2)'))
                .sort(comparer(Array.from(th.parentNode.children).indexOf(th), this.asc = !this.asc))
                .forEach(tr => table.appendChild(tr));
        })));

	</script>
}

<script type="text/javascript">
</script>

Views/Order/Index.cshtml
@model IEnumerable< BABC_Logistics_core.GIS.DTO.OrderHead >

@{
    ViewBag.Title = "Order";
}

<h2>Order</h2>

<div id="search-customer" class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline" method="post">
            @*<select name="search_type">
                <option @{if(ViewBag.search_type == "Datum") "selected" else "") }>Datum</option>
                <option @(ViewBag.search_type=="Kund" ? "selected" : "" )>Kund</option>
                <option @(ViewBag.search_type=="Säljarkod" ? "selected" : "" )>Säljarkod</option>
            </select>*@
            <input name="search_value" type="datetime" value="@ViewBag.search_value" />
            <button type="submit" class="btn btn-primary btn-xs">Sök</button>
        </form>
    </div>
</div>


<p>
    <span class="btn btn-lg">@Html.ActionLink("Create New", "Create")</span>
</p>

<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Kundnr
        </th>
        <th>
            Ordertyp
        </th>
        <th>
            Datum
        </th>
        <th>
            Referens
        </th>
        <th>Knappar</th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliverCustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderType)
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OurReferenceName)
                </td>
                <td>
                    <a class="btn btn-primary tip" href="/Order/Edit/@item.OrderNo" data-toggle="tooltip" data-placement="right" data-original-title="Editera order"><span class="glyphicon glyphicon-ok"></span></a>
                </td>
            </tr>
        }
    }

</table>

Views/Order/PickList.cshtml
@model IEnumerable<BABC_Logistics_core.GIS.DTO.OrderHead>

@{
    ViewBag.Title = "Order";
}
    <meta name="viewport" content="width=device-width, initial-scale=-100%" />
<style>
    #Border {
        border-color: grey;
        border-radius: 20px 70px;
        padding: 30px
    }
    .table{
        margin: 10px 0px;

    }
        .table th {
            background-color: white;
            border-top-color:white;
        }

        .table tr:nth-child(Even) {
            background: #E7E8EC;
        }
       
    
</style>
<div style="background-color:lightgray" id="Border">

    <h1>Plocklista</h1>


    <table id="Table1">
        <tr>

            <td>
                <form class="navbar-form navbar-left"
                      role="search"
                      method="post"
                      action="/Order/PickList">
                    <div class="form-group">
                        <input type="hidden"
                               name="search_type"
                               value="supplie" />
                        <input type="hidden"
                               name="search_value"
                               value="@DateTime.Now.ToString("yyMMdd")" />
                    </div>
                    <button type="submit"
                            class="btn btn-primary @(ViewBag.search_type == "supplie" ? "active btn-success" : "") btn-prog">
                        @BABC_Logistics_core.Language.Resources.PickSupplieOrder
                    </button>
                </form>
            </td>
            
        </tr>
        
    </table>

    






</div>



<table id="myTable" class="table">
  <thead>
      <tr style="cursor:pointer">
          <th>
              <h4> @BABC_Logistics_core.Language.Resources.OrderNo</h4>
          </th>
          <th>
              <h4> @BABC_Logistics_core.Language.Resources.Customer</h4>
          </th>
        
          <th>
              <h4>@BABC_Logistics_core.Language.Resources.DeliveryDate</h4>
          </th>
          <th>
              <h4> @BABC_Logistics_core.Language.Resources.Info</h4>
          </th>
          <th>
              <h4> @BABC_Logistics_core.Language.Resources.Rows</h4>
          </th>
          <th>
              <h4> @BABC_Logistics_core.Language.Resources.Rows2</h4> 
          </th>
     
      </tr>
    </thead>

      
       
    
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderNo)

            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.DeliverCustomerName)
            </td>
            <td>
                @item.PreferedDeliverDate
                
            </td>
           
            
           <td>
                @if (item.PickListState == "9")
                {
                    <span class="badge badge-success">REST</span>
                }
                @if (!string.IsNullOrEmpty(item.CountryCode))
                {
                    <span class="badge badge-info">@item.CountryCode</span>
                }
                @if (item.Relations)
                {
                    <span class="badge badge-danger">IK</span>
                }
                @if (item.isPrioOrder)
                {
                    <span class="badge badge-danger">#!</span>
                }
            </td>

            <td style="text-align:center;">
                @item.OrderRows.Count.ToString()
            </td>
            <td style="text-align:center;">
                @if (item.IsWholeOrderDeliverable == true)
                {
                    <div><span style="">@item.OrderRows.Count</span></div>

                    @*<span class="label label-success">
                    <span class="glyphicon glyphicon-ok"></span>
                </span>*@
                }
                else
                {
                    int sum = @item.OrderRows.Count - @item.NonDeliverableRows;

                    <span style="">@sum</span><span style=""> / </span><span style="color:coral">@item.NonDeliverableRows</span>
                }
            </td>
            <td align="right">
                @if (!ViewBag.search_type.Equals("customer") && item.PickListState != "9")
                {
                    if (item.IsDeliveryAddressUnique == false)
                    {
                        if (item.AdditionalOrders)
                        {

                            <form class="navbar-form navbar-left" role="search" method="post" action="/Order/PickList" target="_blank">
                                <div class="form-group">
                                    <input type="hidden" name="search_type" value="customer" />
                                    <input type="hidden" name="search_value" value="@item.DeliverCustomerNo" />
                                </div>
                                
                            </form>
                        }
                    }
                    
                    <form class="navbar-form navbar-left pull-right" action="Details" role="search" method="post">
                        <input type="hidden" name="id" value="@item.OrderNo" />
                        <button type="submit" class="btn btn-primary">@BABC_Logistics_core.Language.Resources.Details</button>
                    </form>
                }
                else
                {
                    <form class="navbar-form navbar-left pull-right" action="Details" role="search" method="post">
                        <input type="hidden" name="id" value="@item.OrderNo" />
                        <button disabled type="submit" class="btn btn-dark">@BABC_Logistics_core.Language.Resources.Details</button>
                    </form>
                }
            </td>
           
        </tr>
            }
        }
    </tbody>

</table>

<script>
    const getCellValue = (tr, idx) => tr.children[idx].innerText || tr.children[idx].textContent;

    const comparer = (idx, asc) => (a, b) => ((v1, v2) =>
        v1 !== '' && v2 !== '' && !isNaN(v1) && !isNaN(v2) ? v1 - v2 : v1.toString().localeCompare(v2)
    )(getCellValue(asc ? a : b, idx), getCellValue(asc ? b : a, idx));

    // do the work...
    document.querySelectorAll('th').forEach(th => th.addEventListener('click', (() => {
        const table = th.closest('table');
        Array.from(table.querySelectorAll('tr:nth-child(n+2)'))
            .sort(comparer(Array.from(th.parentNode.children).indexOf(th), this.asc = !this.asc))
            .forEach(tr => table.appendChild(tr));
    })));
    if (!Modernizr.inputtypes.date) {
        $("#dateFrom").datepicker(
            { format: "yy-mm-dd" }
        );

        $("#dateTo").datepicker(
            { format: "yy-mm-dd" }
        );
    }

    $("#pg-bar").hide();

   

</script>